" Add vundle and enable
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Plugins
Plugin 'isRuslan/vim-es6'

Plugin 'mileszs/ack.vim'

Plugin 'gmarik/Vundle.vim'

Plugin 'kchmck/vim-coffee-script'

Plugin 'kien/ctrlp.vim'

Plugin 'tpope/vim-fugitive'

Plugin 'scrooloose/nerdtree'

Plugin 'bling/vim-airline'

Plugin 'wombat256.vim'

Plugin 'godlygeek/tabular'

Plugin 'altercation/vim-colors-solarized'

call vundle#end()

filetype plugin indent on

" Decrease timeout lengths to speed up vim responsiveness
set timeout
set timeoutlen=1000
set ttimeoutlen=100

" FIX BACKSPACING
set backspace=indent,eol,start

" THEME SETTINGS
syntax enable
colorscheme wombat256mod

" ENABLE FILETYPE PLUGINS
filetype plugin on

" FOLDING SETTINGS
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

" EDITING HELPERS
" Replace current word with what's in the current register
map <leader>r <ESC>viw"_dP

" SCROLL OFF
:nnoremap <Leader>zz :call ToggleScrollOff()<CR>

function! ToggleScrollOff()
  :if &scrolloff == 999
    set so=5
  :else
    set so=999
  :endif
:endfunction
set so=5

" WHITESPACE MANAGEMENT
" Removes trailing spaces
function! TrimWhiteSpace()
%s/\s*$//
''
:endfunction

set list listchars=trail:.,extends:>
autocmd FileWritePre * :call TrimWhiteSpace()
autocmd FileAppendPre * :call TrimWhiteSpace()
autocmd FilterWritePre * :call TrimWhiteSpace()
autocmd BufWritePre * :call TrimWhiteSpace()

map <F2> :call TrimWhiteSpace()<CR>
map! <F2> :call TrimWhiteSpace()<CR>

" HIGHLIGHTING
let g:indent_guides_auto_colors=0
let g:indent_guides_guide_size=1
hi IndentGuidesOdd  ctermbg=2
hi IndentGuidesEven ctermbg=0
hi SignColumn ctermbg=0

" TABULARIZE SHORTCUTS
map >= :Tabularize /=
map >: :Tabularize /:\zs

" EDITING SETTINGS
" Show status line
set ls=2
set ruler

" Disable backups
set nobackup
set noswapfile

" Buffer control
set hidden

" Tab settings
set nocindent
set smartindent
set autoindent
set smarttab
set expandtab
set tabstop=2
set shiftwidth=2
set list listchars=tab:··,trail:·

" By default, don't wrap and show numbers
set nowrap
set number
set linebreak
set nolist
set showbreak=\ \ \ \

" Highlight current line
set cursorline

" Map leader
let mapleader=" "

" NEXT/PREV BUFFERS
map <leader>[ :bp<CR>
map <leader>] :bn<CR>
map <leader><leader> <C-^>
map <leader>= <C-w>=

" VISUAL UP/DOWN
map <up> gk
map k gk
imap <up> <C-o>gk
map <down> gj
map j gj
imap <down> <C-o>gj
map E ge

" CTRL-P
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|\.hg$\|\.svn$',
  \ 'file': '\.exe$\|\.so$\|\.dll$\|\.DS_Store$',
  \ }

let g:ctrlp_extensions = ['tag', 'buffertag', 'quickfix', 'dir', 'rtscript',
  \ 'undo', 'line', 'changes', 'mixed', 'bookmarkdir']

let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files --cached --exclude-standard --others']

map <leader>gg :CtrlP<CR>
map <leader>b :CtrlPBuffer<CR>
map <leader>m :CtrlPMixed<CR>
map <leader>gr :CtrlPMRU<CR>
map <leader>t :CtrlPBufTag<CR>
map <leader>tt :CtrlPTag<CR>
map <leader>ttt :silent !ctags -R .<CR>

" FILE NAVIGATION
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :edit %%
map <leader>v :view %%

" HIGHLIGHTING
:noremap <leader>h :set hlsearch! hlsearch?<CR>

" WINDOW SIZING
" We have to have a winheight bigger than we want to set winminheight. But if
" we set winheight to be huge before winminheight, the winminheight set will
" fail.
set winheight=10
set winminheight=10
set winheight=999

" TAGLIST
let Tlist_Show_Menu = 1
let Tlist_Use_Right_Window = 1
nnoremap <silent> <leader>ty :TlistToggle<CR>

" NERDTREE
let NERDTreeChDirMode=2
nnoremap <leader>tr :NERDTreeToggle .<CR>

" GUI OPTIONS
if has("gui_running")
  set guioptions=egmt
endif

" DISABLE ARROW KEYS
noremap <Left> <C-w><Left>
noremap <Right> <C-w><Right>
noremap <Down> <C-w><Down>
noremap <Up> <C-w><Up>
inoremap <Left> <Esc><C-w><Left>
inoremap <Right> <Esc><C-w><Right>
inoremap <Down> <Esc><C-w><Down>
inoremap <Up> <Esc><C-w><Up>

" ENABLE POWERLINE FONTS IN AIRLINE
let g:airline_powerline_fonts = 1

" ACK FOR WORD UNDER CURSOR
noremap <Leader>a :Ack '\b<cword>\b'<cr>

