" PATHOGEN
call pathogen#infect()
call pathogen#helptags()

" FIX BACKSPACE
set bs=2

" Decrease timeout lengths to speed up vim responsiveness
set timeout
set timeoutlen=1000
set ttimeoutlen=100


" CLANG COMPLETION
let g:clang_library_path='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib'

" POWERLINE
python from powerline.ext.vim import source_plugin; source_plugin()

" THEME SETTINGS
syntax enable
colorscheme wombat256mod

" FOLDING SETTINGS
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

" Get into ex mode faster
nnoremap ; :

" EDITING HELPERS
" Replace current word with what's in the current register
map <leader>r <ESC>viw"_dP

" SCROLL OFF
:nnoremap <Leader>zz :call ToggleScrollOff()<CR>

function! ToggleScrollOff()
  :if &scrolloff == 999
    set so=5
  :else
    set so=999
  :endif
:endfunction
set so=5

" WHITESPACE MANAGEMENT
" Removes trailing spaces
function! TrimWhiteSpace()
%s/\s*$//
''
:endfunction

set list listchars=trail:.,extends:>
autocmd FileWritePre * :call TrimWhiteSpace()
autocmd FileAppendPre * :call TrimWhiteSpace()
autocmd FilterWritePre * :call TrimWhiteSpace()
autocmd BufWritePre * :call TrimWhiteSpace()

map <F2> :call TrimWhiteSpace()<CR>
map! <F2> :call TrimWhiteSpace()<CR>

" HIGHLIGHTING
let g:indent_guides_auto_colors=0
let g:indent_guides_guide_size=1
hi IndentGuidesOdd  ctermbg=2
hi IndentGuidesEven ctermbg=0
hi SignColumn ctermbg=0

" TABULARIZE SHORTCUTS
map >= :Tabularize /=
map >: :Tabularize /:\zs

" EDITING SETTINGS
" Show status line
set ls=2
set ruler

" Disable backups
set nobackup
set noswapfile

" Buffer control
set hidden

" Tab settings
set cindent
set cinkeys=0{,0},0),:,!^F,o,O,e
set autoindent
set smarttab
set expandtab
set tabstop=2
set shiftwidth=2
set list listchars=tab:··,trail:·

" By default, don't wrap and show numbers
set nowrap
set number
set linebreak
set nolist
set showbreak=\ \ \ \

" Highlight current line
set cursorline

" Map leader
let mapleader="m"

" NEXT/PREV BUFFERS
map <leader>[ :bp<CR>
map <leader>] :bn<CR>
map <leader><leader> <C-^>
map <leader>= <C-w>=

" VISUAL UP/DOWN
map <up> gk
map k gk
imap <up> <C-o>gk
map <down> gj
map j gj
imap <down> <C-o>gj
map E ge

" RAILS-SPECIFIC CTRLP MAPPINGS
map <leader>gac :CtrlPClearCache<cr>\|:CtrlP app/controllers<cr>
map <leader>gav :CtrlPClearCache<cr>\|:CtrlP app/views<cr>
map <leader>gam :CtrlPClearCache<cr>\|:CtrlP app/models<cr>
map <leader>gah :CtrlPClearCache<cr>\|:CtrlP app/helpers<cr>
map <leader>gaa :CtrlPClearCache<cr>\|:CtrlP app/assets<cr>
map <leader>gj :CtrlPClearCache<cr>\|:CtrlP public/javascripts<cr>
map <leader>gc :CtrlPClearCache<cr>\|:CtrlP public/coffeescripts<cr>
map <leader>gs :CtrlPClearCache<cr>\|:CtrlP public/stylesheets<cr>
map <leader>gf :CtrlPClearCache<cr>\|:CtrlP features<cr>
map <leader>gt :CtrlPClearCache<cr>\|:CtrlP spec<cr>
map <leader>gp :CtrlPClearCache<cr>\|:CtrlP services/api<cr>
map <leader>gl :CtrlPClearCache<cr>\|:CtrlP lib<cr>

" CTRL-P
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|\.hg$\|\.svn$',
  \ 'file': '\.exe$\|\.so$\|\.dll$\|\.DS_Store$',
  \ }

let g:ctrlp_extensions = ['tag', 'buffertag', 'quickfix', 'dir', 'rtscript',
  \ 'undo', 'line', 'changes', 'mixed', 'bookmarkdir']

let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files --cached --others']

map <leader>gg :CtrlP<CR>
map <leader>b :CtrlPBuffer<CR>
map <leader>m :CtrlPMixed<CR>
map <leader>gr :CtrlPMRU<CR>
map <leader>tt :silent !ctags %<CR> :CtrlPBufTag<CR>

" FILE NAVIGATION
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :edit %%
map <leader>v :view %%

" HIGHLIGHTING
:noremap <leader>h :set hlsearch! hlsearch?<CR>

" WINDOW SIZING
" We have to have a winheight bigger than we want to set winminheight. But if
" we set winheight to be huge before winminheight, the winminheight set will
" fail.
set winheight=5
set winminheight=5
set winheight=999

" TAGLIST
let Tlist_Show_Menu = 1
let Tlist_Use_Right_Window = 1
nnoremap <silent> <leader>ty :TlistToggle<CR>

" NERDTREE
let NERDTreeChDirMode=2
nnoremap <leader>tr :NERDTreeToggle .<CR>

" GUI OPTIONS
if has("gui_running")
  set guioptions=egmt
endif

" DISABLE ARROW KEYS
noremap <Left> <C-w><Left>
noremap <Right> <C-w><Right>
noremap <Down> <C-w><Down>
noremap <Up> <C-w><Up>
inoremap <Left> <Esc><C-w><Left>
inoremap <Right> <Esc><C-w><Right>
inoremap <Down> <Esc><C-w><Down>
inoremap <Up> <Esc><C-w><Up>
